## 第二章 NumPy入门

用`np`别名导入Numpy

In [1]:
import numpy as np

使用`np.array`从Python列表创建数组

In [2]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

Numpy要求数组必须包含同一类型的数据。如果类型不匹配，Numpy将会向上转换（如果可行）

In [3]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

如果明确希望设置数组的数据类型，可以用`dtype`关键字

In [4]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

创建一个长度为10的数组，数组的值都是0

In [5]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

创建一个3×5的浮点型数组，数组的值都是1

In [6]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

创建一个3×5的浮点型数组，数组的值都是3.14

In [7]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

创建一个3×5的浮点数数组，数组的值是一个线性序列  
从0开始，到20结束，步长为2

In [8]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

创建一个5个元素的数组，这5个数均匀地分配到0～1

In [9]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

创建一个3×3的、在0～1均匀分布的随机数组成的数组

In [10]:
np.random.random((3, 3))

array([[0.52626552, 0.22228005, 0.81477298],
       [0.31813873, 0.08884351, 0.68015197],
       [0.20551655, 0.86493518, 0.01726508]])

创建一个3×3的、均值为0、方差为1的正太分布的随机数数组

In [13]:
np.random.normal(0, 1, (3, 3))

array([[ 0.99283415, -1.71249979, -0.55393537],
       [ 0.8074851 ,  0.72441903, -0.43407665],
       [-0.15590456,  0.02184144,  0.13633828]])

创建一个3×3的、[0, 10]区间的随机整型数组

In [14]:
np.random.randint(0, 10, (3, 3))

array([[7, 0, 4],
       [4, 7, 9],
       [3, 3, 8]])

创建一个3×3的单位矩阵

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

创建一个由3个整型数组成的未初始化的数组  
数组中的值是任意值

In [16]:
np.empty(3)

array([1., 1., 1.])

每个数组都有如下属性：
- `nidm`：数组的维度
- `shape`：数组每个维度的大小
- `size` 数组的总大小
- `dtype` 数组的数据类型
- `itemsize` 每个数组元素字节大小
- `nbytes` 数组总字节大小  

一般来说，可以认为`nbytes`与`itemsize`和`size`的乘积大小相等

In [25]:
np.random.seed(0) # 设置随机数种子

x1 = np.random.randint(10, size=6) # 一维数组
x2 = np.random.randint(10, size=(3, 4)) # 二维数组
x3 = np.random.randint(10, size=(3, 4, 5)) # 三维数组

print(x2)
print("x2 ndim:", x2.ndim)
print("x2 shape:", x2.shape)
print("x2 size:", x2.size)
print("x2 itemsize:", x2.itemsize)
print("x2 nbytes", x2.nbytes)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
x2 ndim: 2
x2 shape: (3, 4)
x2 size: 12
x2 itemsize: 8
x2 nbytes 96


一维数组获取单个元素

In [27]:
print(x1)
print(x1[0]) # 获取第一个元素
print(x1[-1]) # 获取最后一个元素

[5 0 3 3 7 9]
5
9


二维数组获取单个元素

In [33]:
print(x2)
print(x2[0, 0])
print(x2[2, -1])

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
3
7


注意⚠️：NumPy数组是固定类型的，如果将一个浮点数插入到一个整型数组中，浮点值将会被截断，并且不会有任何提示

In [31]:
x1[0] = 3.14159
x1

array([3, 0, 3, 3, 7, 9])

#### 2.2.3 数组切片  
语法：`x[start:stop:step]`  
`start`默认值为`0`  
`stop`默认为维度的大小  
`step`默认值为`1`

数组切片返回的是数组的视图，而不是数据的副本，修改子数组，原始数组也会被修改

**一维数组**

In [36]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
x[:5] # 前5个元素

array([0, 1, 2, 3, 4])

In [39]:
x[5:] # 索引5之后的元素

array([5, 6, 7, 8, 9])

In [41]:
x[4:7] #索引4到索引7之间的元素（含头不含尾）

array([4, 5, 6])

In [42]:
x[::2] # 隔一个元素

array([0, 2, 4, 6, 8])

In [43]:
x[1::2] # 隔一个元素，从索引1开始

array([1, 3, 5, 7, 9])

In [44]:
x[::-1] # 所有元素逆序

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [45]:
x[5::-2] # 从索引5开始每隔一个元素逆序

array([5, 3, 1])

**多维数组**

In [48]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [53]:
x2[:2, :3] # 两行，三列

array([[3, 5, 2],
       [7, 6, 8]])

In [54]:
x2[:3, ::2] # 所有行，每隔一列

array([[3, 2],
       [7, 8],
       [1, 7]])

In [55]:
x2[::-1, ::-1] # 逆序

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

**获取数组的行与列**

In [61]:
x2[:, 0] # x2的第一列

array([3, 7, 1])

`:`表示空切片

In [63]:
x2[0, :] # x2的第一行
# x2[0] 等效

array([3, 5, 2, 4])